web/router.ex
defmodule Seriex.Router do
  use Seriex.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Seriex do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/series", SeriesController, :index
    get "/series/:id", SeriesController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", Seriex do
  #   pipe_through :api
  # end
end

lib/seriex/endpoint.ex
defmodule Seriex.Endpoint do
  use Phoenix.Endpoint, otp_app: :seriex

  socket "/socket", Seriex.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :seriex, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_seriex_key",
    signing_salt: "FC1c/Gm7"

  plug Seriex.Router
end

lib/seriex/eztv.ex
defmodule EZTV do
  @base_url "https://eztv.ag"

  def get_magnet(name: name, season: season, episode: episode) do
    ep = episode |> Integer.to_string |> String.rjust(2, ?0)
    s = season |> Integer.to_string |> String.rjust(2, ?0)
    path = "/search/#{name} S#{s}E#{ep} 720p"

    request(path)
  end

  def fetch(id) do
    path = "/shows/#{id}?embed=episodes"
    request(path)
  end

  defp request(path) do
    @base_url <> path
    |> URI.encode
    |> HTTPoison.get!
    |> parse_request
  end

  defp parse_request(%{status_code: 200, body: body}) do
    Floki.find(body, "a.magnet") |> Floki.attribute("href") |> List.first
  end
end

lib/seriex/tvdb.ex
defmodule TVMaze do
  @base_url "http://api.tvmaze.com"

  def search(title) do
    path = "/search/shows?q=#{title}"
    request(path)
  end

  def fetch(id) do
    path = "/shows/#{id}?embed=episodes"
    request(path)
  end

  defp request(path) do
    @base_url <> path
    |> URI.encode
    |> HTTPoison.get!
    |> parse_request
  end

  defp parse_request(%{status_code: 200, body: body}) do
    Poison.Parser.parse! body
  end
end

lib/seriex/tvmaze.ex
defmodule TVMaze do
  @base_url "http://api.tvmaze.com"

  def search(title) do
    path = "/search/shows?q=#{title}"
    request(path)
  end

  def fetch(id) do
    path = "/shows/#{id}?embed=episodes"
    request(path)
  end

  defp request(path) do
    @base_url <> path
    |> URI.encode
    |> HTTPoison.get!
    |> parse_request
  end

  defp parse_request(%{status_code: 200, body: body}) do
    Poison.Parser.parse! body
  end
end

web/controllers/page_controller.ex
defmodule Seriex.PageController do
  use Seriex.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/series_controller.ex
defmodule Seriex.SeriesController do
  use Seriex.Web, :controller

  def index(conn, %{"q" => query}) do
    shows = TVMaze.search(query)
    render conn, "index.html", shows: shows
  end

  def index(conn, _params) do
    render conn, "index.html", shows: []
  end

  def show(conn, %{"id" => id}) do
    serie = TVMaze.fetch(id)

    render conn, "show.html", serie: serie
  end
end

web/views/error_view.ex
defmodule Seriex.ErrorView do
  use Seriex.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Seriex.LayoutView do
  use Seriex.Web, :view
end

web/views/page_view.ex
defmodule Seriex.PageView do
  use Seriex.Web, :view
end

web/views/series_view.ex
defmodule Seriex.SeriesView do
  use Seriex.Web, :view

  def seasons(%{"_embedded" => %{"episodes" => episodes}}) do
    episodes |> Enum.chunk_by(&(&1["season"]))
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Phoenix!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  </head>

  <body>
    <div class="container" role="main">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
        </ul>
        <span class="logo"></span>
      </div>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= @inner %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2>Welcome to Phoenix!</h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="http://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/series/index.html.eex
<h2>Search results:</h2>
<form class="" action="/series" method="get">
  <input type="text" name="q" value="">
</form>

<ul>
  <%= for show <- @shows do %>
    <li><%= show["show"]["name"] %></li>
    <a href="<%= series_path(@conn, :show, show["show"]["id"]) %>">
      <img src="<%=show["show"]["image"]["medium"]%>" alt="" />
    </a>
  <% end %>
</ul>

web/templates/series/show.html.eex
<h1><%= @serie["name"] %></h1>

<ul>
  <%= for season <- @serie |> seasons do %>
    <h3>Season <%= season |> List.first |> Dict.get("season") %></h3>
    <%= for episode <- season do %>
      <li><%= "#{episode["name"]} - S#{episode["season"]}E#{episode["number"]}" %></li>
    <% end %>
  <% end %>
</ul>